"""Selectors for searching html elements"""
staff_btn_selector = "a.staff-btn"
add_btn_selector = 'button.chdc-button__small.mdc-button--unelevated'
narrative_area_selector = 'header.datasheet-head app-text-field-editor-cell > div.cell-wrapped.editable'
narrative_input_selector = 'textarea[placeholder="Enter Narrative"]'
loctype_area_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(3) div.cell-wrapped.editable'
loctype_input_selector = "input.mat-mdc-input-element[placeholder='Search Location Type']"
actor1_area_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(7) div.cell-wrapped.editable'
actor1_input_selector = 'input.mat-mdc-input-element[placeholder="Search Actor 1 (Perpetrator)"]'
actor1_path_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(7) div.cell-options > div.path-preview'
actor2_area_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(8) div.cell-wrapped.editable'
actor2_input_selector = 'input.mat-mdc-input-element[placeholder="Search Actor 2 (Target)"]'
actor2_path_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(8) div.cell-options > div.path-preview'
act_area_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(9) div.cell-wrapped.editable'
act_input_selector = 'input.mat-mdc-input-element[placeholder="Search Act"]'
act_path_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(9) div.cell-options > div.path-preview'
act_attempted_selector = 'input[value="act-result:attempted"]'
source_area_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(19) div.cell-wrapped.editable'
source_input_selector = 'input.mat-mdc-input-element[placeholder="Search Source"]'
location_area_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(2) div.cell-wrapped.editable'
location_li_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(2) ul > li[title="{title}"]'
datetime_area_selector = 'div.datasheet-body.p-4.ng-star-inserted > div:nth-child(1) > div > app-datetime-editor-cell > div'
calendar_button_selector = 'button[aria-label="Open calendar"]'
month_year_choosing_selector = 'button[aria-label="Choose month and year"]'
year_button_selector = 'button[aria-label="{year}"]'
month_button_selector = 'button[aria-label="{month} {year}"]'
day_button_selector = 'button[aria-label="{month} {day}, {year}"]'
remove_time_button_xpath = '//button[contains(., "Remove time")]'
hour_field_selector = 'input[formcontrolname="hour"]'
minute_field_selector = 'input[formcontrolname="minute"]'
apply_date_xpath = '//button[@ngxmatdatepickerapply]'
submit_button_selector = 'button[data-testid="submit-button"]'
simple_li_selector = 'li[title="{title}"]'
splash_screen_selector = 'chdc-splash-screen.ng-star-inserted'
email_field_selector = 'input.form-control[placeholder="Enter your INSO email address"]'
pass_field_selector = 'input.form-control[type="password"]'
chdc_title_text = "INSO CHDC"
next_btn_selector = 'input.win-button[type="submit"]'
modal_window_selector = 'mat-dialog-container[aria-modal="true"]'
modal_close_btn_selector = 'chdc-info-dialog > div > header > button.mat-icon-button'
radio_group_selector = 'div.editable.valid > div.radio-options > mat-radio-group'
incident_id_selector = 'div.incident-overview-title > span.px-1.cursor-pointer.chdc-status-incomplete-color'
