"""Selectors for searching html elements"""
add_btn_selector = 'button.chdc-button__small.mdc-button--unelevated'
narrative_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > header > div.datasheet-body > div > div > app-text-field-editor-cell > div'
narrative_input_selector = 'textarea[placeholder="Enter Narrative"]'
loctype_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(3) > div > app-select-editor-cell > div'
loctype_input_selector = "input.mat-mdc-input-element[placeholder='Search Location Type']"
datasheet_body_selector = 'div.datasheet-body.p-4.ng-star-inserted'
submit_date_button_selector = '#cdk-overlay-25 > ngx-mat-datepicker-content > div.mat-datepicker-content-container.ng-tns-c47-657.mat-datepicker-content-container-with-actions.mat-datepicker-content-container-with-time > div.mat-datepicker-actions.ng-star-inserted > div:nth-child(2) > button.chdc-button-flat-main-dark.mdc-button.mdc-button--raised.mat-mdc-raised-button.mat-primary.mat-mdc-button-base'
actor1_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(7) > div > app-select-editor-cell > div'
actor1_input_selector = 'input.mat-mdc-input-element[placeholder="Search Actor 1 (Perpetrator)"]'
actor2_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(8) > div > app-select-editor-cell > div'
actor2_input_selector = 'input.mat-mdc-input-element[placeholder="Search Actor 2 (Target)"]'
act_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(9) > div > app-act-editor-cell > div'
act_input_selector = 'input.mat-mdc-input-element[placeholder="Search Act"]'
source_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(19) > div > app-select-editor-cell > div'
source_input_selector = 'input.mat-mdc-input-element[placeholder="Search Source"]'
location_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(2) > div > app-select-editor-cell > div'
location_li_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(2) > div > app-select-editor-cell > div > div.cell-options.ng-star-inserted > ul > li[title="{title}"]'
datetime_area_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(1) > div > app-datetime-editor-cell > div'
calendar_button_selector = 'button[aria-label="Open calendar"]'
month_year_choosing_selector = 'button[aria-label="Choose month and year"]'
year_button_selector = 'button[aria-label="{year}"]'
month_button_selector = 'button[aria-label="{month} {year}"]'
day_button_selector = 'button[aria-label="{month} {day}, {year}"]'
remove_time_button_xpath = '//button[contains(., "Remove time")]'
hour_field_selector = 'input[formcontrolname="hour"]'
minute_field_selector = 'input[formcontrolname="minute"]'
apply_date_xpath = '//button[@ngxmatdatepickerapply]'
submit_button_selector = 'button[data-testid="submit-button"]'
simple_li_selector = 'li[title="{title}"]'
actor1_path_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(7) > div > app-select-editor-cell > div > div.cell-options.ng-star-inserted > div'
actor2_path_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(8) > div > app-select-editor-cell > div > div.cell-options.ng-star-inserted > div'
act_path_selector = '#app > layout > dense-layout > div > div.flex.flex-1.flex-row > incidents-datatable > div > mat-drawer-container > mat-drawer > div > app-sidebar-sheet > article > div.datasheet-body.p-4.ng-star-inserted > div:nth-child(9) > div > app-act-editor-cell > div > div.cell-options.ng-star-inserted > div.path-preview.ng-star-inserted'
